import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  //login
  logincontainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  loginbuttoncontainer: {
    marginTop: 172,
  },
  logo: {
    width: 100,
    height: 40,
  },
  loginlogo: {
    marginTop: 164,
    width: 166,
    height: 152,
    resizeMode: "contain",
  },
  customTuner: {
    marginTop: 20,
    marginLeft: 21,
    width: 150,
    height: 215,
    flexShrink: 0,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    shadowColor: "#7279DF",
    shadowOffset: {
      width: 0,
      height: 3.843583106994629,
    },
    shadowOpacity: 0.1,
    shadowRadius: 17,
    elevation: 17,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  nestedContainer: {
    marginTop: 29,
    marginLeft: 31,
    width: 88,
    height: 88,
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
    backgroundColor: "#B29BF2",
    borderRadius: 29,
  },
  tutorContainer: {
    marginTop: 16,
    marginLeft: 24,
  },
  tutorName: {
    color: "#000",
    fontSize: 16,
    fontWeight: "600",
  },
  tutorSubject: {
    color: "#5F5F5F",
    fontSize: 12,
    fontWeight: "400",
    marginTop: 4,
  },
  favoriteContainer: {
    marginTop: 16,
    marginLeft: 24,
    flexDirection: "row",
    alignItems: "center",
  },
  favoriteText: {
    color: "#5884E8",
    fontSize: 12,
    fontWeight: "600",
    marginLeft: 8,
  },
  //
  centeredContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "flex-end", // 아이템을 오른쪽으로 정렬합니다.
    paddingRight: 16, // 위치를 조정하기 위해 오른쪽에 약간의 여유를 둡니다.
  },
  longcustomTuner: {
    marginTop: 20,
    marginLeft: 21,
    width: 357,
    height: 98,
    flexShrink: 0,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    shadowColor: "#7279DF",
    shadowOffset: {
      width: 0,
      height: 3.843583106994629,
    },
    shadowOpacity: 0.1,
    shadowRadius: 17,
    elevation: 17,
    flexDirection: "row",
  },
  longnestedContainer: {
    marginTop: 21,
    marginLeft: 21,
    width: 56,
    height: 56,
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
    backgroundColor: "#B29BF2",
    borderRadius: 28,
  },
  tutorinformationContainer: {
    justifyContent: "center",
  },
  longtunerName:{
    marginTop: 21,
    marginLeft: 16,
    color: "#000",
    fontSize: 16,
    fontWeight: "600",
  },
  longtunerSubject:{
    marginTop: 4,
    marginLeft: 16,
    color: "#5F5F5F",
    fontSize: 12,
    fontWeight: "400",
  },
  longfavoriteContainer: {
    marginTop: 8,
    marginLeft: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  longfavoriteText:{
    color: "#5884E8",
    marginLeft: 4,
  },
  selectButtonContainer: {
    alignItems: "flex-end",
    marginBottom: 8,
  },
  selectButton: {
    marginTop: 8,
    marginLeft: 16,
    width: 56,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#5884E8",
    justifyContent: "center",
    alignItems: "center",
  },
selectButtonText: {
  color : "#ffffff",
},
  //eixtbutton
  exitButtonContainer: {
    width: 328,
    height: 244,
    backgroundColor: "#ffffff",
    position: "absolute",
    top: 300,
    left: 32,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
    elevation: 1,
    textAlign: "center",
    borderWidth: 1,
    borderColor: "#ADADAD",
  },
  textratingContainer: {},
  ratingButtonContainer: {
    width: 328,
    height: 244,
    backgroundColor: "#ffffff",
    position: "absolute",
    top: 300,
    left: 32,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
    elevation: 1,
    textAlign: "center",
    borderWidth: 1,
    borderColor: "#ADADAD",
  },
  errorImage: {
    width: 48,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  exittext1: {
    fontSize: 20,
    color: "#717171",
    marginBottom: 4,
  },
  exittext2: {
    fontSize: 15,
    color: "#717171",
  },
  returnButton: {
    width: 124,
    height: 36,
    backgroundColor: "#5884E8",
    borderRadius: 10,
    justifyContent: "center",
    marginRight: 8,
  },
  returnText: {
    textAlign: "center",
    fontSize: 14,
    color: "#ffffff",
    fontWeight: "700",
    lineHeight: 18,
    letterSpacing: -0.5,
  },
  endButton: {
    width: 124,
    height: 36,
    backgroundColor: "#FF6565",
    borderRadius: 10,
    justifyContent: "center",
    marginLeft: 8,
  },
  endText: {
    textAlign: "center",
    fontSize: 14,
    color: "#ffffff",
    fontWeight: "700",
    lineHeight: 18,
    letterSpacing: -0.5,
  },
  checkImage: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  endText1: {
    fontSize: 20,
    color: "#717171",
    marginBottom: 4,
    textAlign: "center",
  },
  endText2: {
    fontSize: 16,
    color: "#717171",
    textAlign: "center",
  },
  ratingContainer: {
    marginLeft: 40,
    marginTop: 16,
    width: 148,
    alignItems: "center",
  },
  kindContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  tipsContainer: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  ratingText1: {
    fontSize: 12,
    color: "#414141",
    textAlign: "center",
    marginRight: 4,
  },
  ratingText2: {
    fontSize: 12,
    color: "#414141",
    textAlign: "center",
  },
  starContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  starImage: {
    width: 24,
    height: 24,
  },
  closeButton: {
    width: 124,
    height: 28,
    backgroundColor: "#5884E8",
    borderRadius: 10,
    justifyContent: "center",
    textAlign: "center",
    marginTop: 16,
  },
  closeText: {
    textAlign: "center",
    fontSize: 14,
    color: "#ffffff",
    fontWeight: "700",
    lineHeight: 18,
    letterSpacing: -0.5,
  },
});

export default styles;