import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  logincontainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  loginbuttoncontainer: {
    marginTop: 172,
  },
  logo: {
    width: 100,
    height: 40,
  },
  loginlogo: {
    marginTop: 164,
    width: 166,
    height: 152,
    resizeMode: "contain",
  },
  customTuner: {
    marginTop: 20,
    marginLeft: 21,
    width: 150,
    height: 215,
    flexShrink: 0,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    shadowColor: "#7279DF",
    shadowOffset: {
      width: 0,
      height: 3.843583106994629,
    },
    shadowOpacity: 0.1,
    shadowRadius: 17,
    elevation: 17,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  nestedContainer: {
    marginTop: 29,
    marginLeft: 31,
    width: 88,
    height: 88,
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
    backgroundColor: "#B29BF2",
    borderRadius: 29,
  },
  //longcustomTuner
  longcustomTuner: {
    marginTop: 20,
    marginLeft: 21,
    width: 357,
    height: 98,
    flexShrink: 0,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    shadowColor: "#7279DF",
    shadowOffset: {
      width: 0,
      height: 3.843583106994629,
    },
    shadowOpacity: 0.1,
    shadowRadius: 17,
    elevation: 17,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  longnestedContainer: {
    marginTop: 21,
    marginLeft: 21,
    width: 56,
    height: 56,
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
    backgroundColor: "#B29BF2",
    borderRadius: 28,
  },
  //eixtbutton
  exitButtonContainer: {
    width: 328,
    height: 244,
    backgroundColor: "#ffffff",
    position: "absolute",
    top: 300,
    left: 32,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
    elevation: 1,
    textAlign: "center",
    borderWidth: 1,
    borderColor: "#ADADAD",
  },
  textratingContainer: {},
  ratingButtonContainer: {
    width: 328,
    height: 244,
    backgroundColor: "#ffffff",
    position: "absolute",
    top: 300,
    left: 32,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
    elevation: 1,
    textAlign: "center",
    borderWidth: 1,
    borderColor: "#ADADAD",
  },
  errorImage: {
    width: 48,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  exittext1: {
    fontSize: 20,
    color: "#717171",
    marginBottom: 4,
  },
  exittext2: {
    fontSize: 15,
    color: "#717171",
  },
  returnButton: {
    width: 124,
    height: 36,
    backgroundColor: "#5884E8",
    borderRadius: 10,
    justifyContent: "center",
    marginRight: 8,
  },
  returnText: {
    textAlign: "center",
    fontSize: 14,
    color: "#ffffff",
    fontWeight: "700",
    lineHeight: 18,
    letterSpacing: -0.5,
  },
  endButton: {
    width: 124,
    height: 36,
    backgroundColor: "#FF6565",
    borderRadius: 10,
    justifyContent: "center",
    marginLeft: 8,
  },
  endText: {
    textAlign: "center",
    fontSize: 14,
    color: "#ffffff",
    fontWeight: "700",
    lineHeight: 18,
    letterSpacing: -0.5,
  },
  checkImage: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  endText1: {
    fontSize: 20,
    color: "#717171",
    marginBottom: 4,
    textAlign: "center",
  },
  endText2: {
    fontSize: 16,
    color: "#717171",
    textAlign: "center",
  },
  ratingContainer: {
    marginLeft: 40,
    marginTop: 16,
    width: 148,
    alignItems: "center",
  },
  kindContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  tipsContainer: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  ratingText1: {
    fontSize: 12,
    color: "#414141",
    textAlign: "center",
    marginRight: 4,
  },
  ratingText2: {
    fontSize: 12,
    color: "#414141",
    textAlign: "center",
  },
  starContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  starImage: {
    width: 24,
    height: 24,
  },
  closeButton: {
    width: 124,
    height: 28,
    backgroundColor: "#5884E8",
    borderRadius: 10,
    justifyContent: "center",
    textAlign: "center",
    marginTop: 16,
  },
  closeText: {
    textAlign: "center",
    fontSize: 14,
    color: "#ffffff",
    fontWeight: "700",
    lineHeight: 18,
    letterSpacing: -0.5,
  },
});

export default styles;