import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  greeting: {
    marginLeft: 10,
    fontSize: 20,
    fontWeight: "bold",
  },
  profileImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 8,
  },
  banner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: "auto",
    height: 212,
    backgroundColor: "#498DE8",
    borderRadius: 20,
    alignSelf: "center",
    marginVertical: 5,
  },
  bannertext: {
    marginLeft: 7,
    marginTop: 46,
  },
  bannertext1: {
    width: 92,
    height: 24,
    flexShrink: 0,
    color: "#FFF",
    textAlign: "center",
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 18,
    letterSpacing: -0.5,
  },
  bannertext2: {
    width: 128,
    flexShrink: 0,
    color: "#FFF",
    textAlign: "center",
    fontSize: 36,
    fontWeight: "600",
    lineHeight: 36,
    letterSpacing: -0.5,
  },
  bannerimage: {
    marginRight: 9,
    marginTop: 12,
    width: 200,
    height: 160,
    flexShrink: 0,
  },
  title: {
    marginLeft: 24,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
  },
  titleText: {
    marginLeft: 4,
    color: "#000",
    fontSize: 18,
    fontStyle: "normal",
    fontWeight: "600",
    lineHeight: 22,
  },
  moreHomeContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  moreHome: {
    width: "auto",
    height: 20,
    flexShrink: 0,
    color: "#5884E8",
    textAlign: "center",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 18,
    marginRight: 24,
    marginTop: 20,
  },
  levelupContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  levelup: {
    marginTop: 20,
    width: 25,
    height: 26,
    marginLeft: 20,
    flexShrink: 0,
  },
  leveltext: {
    marginTop: 24,
    width: 90,
    height: "auto",
    flexShrink: 0,
    color: "#000",
    textAlign: "center",
    fontSize: 20,
    fontWeight: "700",
  },
  leveltext2: {
    marginLeft: 24,
    marginTop: 8,
    width: "auto",
    height: 20,
    flexShrink: 0,
    fontSize: 11,
  },
  studylevel: {
    marginTop: 20,
    width: "auto",
    height: 110,
    marginLeft: 24,
    marginRight: 24,
    borderRadius: 12,
    backgroundColor: "#ffffff",
  },
});

export default styles;
