import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 20,
    marginRight: 8,
  },
  title: {
    flexDirection: "row",
    alignItems: "center",
  },
  kebabIcon: {
    width: 28,
    height: 28,
  },
  commentContainer: {
    width: "auto",
    height: 360,
    backgroundColor: "#ffffff",
    marginLeft: 20,
    marginRight: 20,
    marginTop: 16,
    borderRadius: 12,
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#D0D0D0",
    borderWidth: 1,
  },
  textInput: {
    width: 140,
    height: 40,
  },
  placeholderText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    color: "#5e5e5e",
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  postTitleText: {
    flexDirection: "row",
    alignItems: "center",
  },
  postName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000", 
  },
  postDate: {
    fontSize: 14,
    color: "#666", 
  },
  
  commentInputContainer: {
    width: "auto",
    height: 48,
    backgroundColor: "#ffffff",
    marginLeft: 20,
    marginRight: 20,
    marginTop: 16,
    borderRadius: 12,
    borderColor: "#D0D0D0",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
  },
  commentBar: {
    flexDirection: "column",
    alignItems: "flex-start", 
    padding: 8,
    marginTop: 8, 
  },  
  commentInnerBar:{
    flexDirection: "row",
    alignItems: "left",
  },
  commentComponent: {
    backgroundColor: "#ffffff",
    width: 288,
    height: 58,
    marginLeft: 8,
    borderColor: "#D0D0D0",
    borderWidth: 1,
    borderRadius: 12,
  },
  commentNameText: {
    fontSize: 12,
    lineHeight: 20,
    fontWeight: "600",
    color: "#000",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
    marginTop: 8,
  },
  commentDetailText: {
    color: "#5f5f5f",
    fontSize: 12,
    fontWeight: "400",
    marginLeft: 8,
  },
  commentFavorite: {
    alignItems: "flex-start", 
    flexDirection: "row",
    marginLeft: 40,
    marginTop: 8,
  },
  commentfavoriteText: {
    color: "#5f5f5f",
    fontSize: 12,
    fontWeight: "400",
    marginLeft: 4,
  },
  sendIcon: {
    width: 24,
    height: 24,
    marginLeft: 12,
    marginRight: 12,
  },
});

export default styles;