import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f5f5f5",
  },
  title: {
    marginLeft: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
    flex: 1,
  },
  titleText: {
    color: "#000",
    fontSize: 26,
    fontStyle: "normal",
    fontWeight: "700",
  },
  profileImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 8,
  },
  messageContainer: {
    display: "flex",
    width: "auto",
    marginRight: 24,
    height: "85%",
    flexDirection: "column",
    alignItems: "flex-start",
    flexShrink: 0,
    borderRadius: 12,
    backgroundColor: "#FFF",
    marginLeft: 24,
  },
  chatContainer: {
    width: "auto",
    minHeight: 56,
    paddingRight: 12,
    paddingLeft: 12,
    paddingBottom: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  textContainer: {
    display: "flex",
    width: "80%",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 2,
  },
  nameContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  nestedContainer: {
    marginLeft: 4,
    marginRight: 12,
    width: 49,
    height: 49,
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
    backgroundColor: "#B29BF2",
    borderRadius: 10,
  },
  contextContainer: {
    flexDirection: "row",
    height: 20,
    justifyContent: "center",
    alignItems: "flex-start",
    gap: 2,
  },
  name: {
    color: "#0F1828",
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 24,
  },
  context: {
    color: "#ADB5BD",
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 20,
    letterSpacing: -0.5,
  },
  time: {
    color: "#000",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 16,
  },
});

export default styles;
